# SPDX-FileCopyrightText: 2026 KustoKing / SecM8
# SPDX-License-Identifier: Apache-2.0

"""Markdown renderer for :class:`contentops.catalog.inspect.Inventory`.

Pure function: same Inventory in → byte-identical markdown out. The
output is committed to ``docs/reference/generated-catalog.md`` and
its drift is enforced by ``contentops catalog check`` in CI.
"""

from __future__ import annotations

from contentops.catalog.inspect import Inventory


# Path (repo-relative) where the rendered catalog lives. Single source
# of truth so the CLI commands and tests agree.
GENERATED_FILE = "docs/reference/generated-catalog.md"


_HEADER = """\
# Generated catalog

> **Generated.** Do not edit this file by hand. Regenerate with
> `contentops catalog regenerate`. CI gate: `contentops catalog check`
> exits 1 when this file disagrees with what the code would currently
> produce. Source of truth lives in `contentops/catalog/inspect.py`.

This catalog is a code-derived projection of the live contentops state:
the registered Click commands, a command -> entrypoint -> workflow
traceability matrix, the asset taxonomy, the lint-rule registry, the
per-asset handlers, the GitHub Actions workflows, and the unit +
integration test files. Hand-curated narrative catalogs
(`feature-catalog.md`, `test-catalog.md`, `cli-workflow-matrix.md`,
`asset-coverage.md`) keep their prose; this file is what survives
drift.
"""


def _render_commands(inv: Inventory) -> str:
    lines = ["## CLI commands", "", "| Command | Type | Summary |", "|---|---|---|"]
    for c in inv.commands:
        kind = "group" if c.is_group else "command"
        summary = c.help_summary.replace("|", "\\|")
        lines.append(f"| `{c.name}` | {kind} | {summary} |")
    lines.append("")
    return "\n".join(lines)


def _render_traceability(inv: Inventory) -> str:
    lines = [
        "## Command traceability (Action -> Function -> Script -> Workflow)",
        "",
        (
            "Every registered command, the Click callback that implements "
            "it (the Function), the module that defines it (the Script), "
            "and the GitHub Actions workflow(s) that invoke it. "
            "`_(local-only)_` means no workflow runs it; `_(group)_` is a "
            "command group with no callback of its own."
        ),
        "",
        "| Command | Entrypoint function | Module | Workflow(s) |",
        "|---|---|---|---|",
    ]
    for t in inv.traceability:
        # Pipe-escape every cell for GFM-table safety, mirroring
        # _render_commands. Values are Click/Python introspection
        # identifiers + .yml paths (no pipes today), so this is
        # consistency insurance, not a live fix.
        command = t.command.replace("|", "\\|")
        cb = t.callback.replace("|", "\\|")
        mod = t.module.replace("|", "\\|")
        fn = f"`{cb}`" if t.callback else "_(group)_"
        module = f"`{mod}`" if t.module else "—"
        escaped_workflows = [w.replace("|", "\\|") for w in t.workflows]
        workflows = (
            ", ".join(f"`{w}`" for w in escaped_workflows)
            if escaped_workflows else "_(local-only)_"
        )
        lines.append(f"| `{command}` | {fn} | {module} | {workflows} |")
    lines.append("")
    return "\n".join(lines)


def _render_assets(inv: Inventory) -> str:
    lines = [
        "## Asset taxonomy",
        "",
        f"Total: **{len(inv.assets)}** asset kinds (six-kind detection-engineering taxonomy).",
        "",
        "| Asset kind | Handler module | KQL field declared |",
        "|---|---|---|",
    ]
    for a in inv.assets:
        kql = "yes" if a.has_kql_field else "no"
        lines.append(f"| `{a.name}` | `{a.handler_module}` | {kql} |")
    lines.append("")
    return "\n".join(lines)


def _render_lint_rules(inv: Inventory) -> str:
    lines = [
        "## Lint rules",
        "",
        "| Rule ID | Severity | Module |",
        "|---|---|---|",
    ]
    for r in inv.lint_rules:
        lines.append(f"| `{r.rule_id}` | {r.severity} | `{r.module}` |")
    lines.append("")
    return "\n".join(lines)


def _render_handlers(inv: Inventory) -> str:
    lines = [
        "## Handlers",
        "",
        "| Module | File | Asset kind |",
        "|---|---|---|",
    ]
    for h in inv.handlers:
        asset = h.asset_kind or "_(unmapped)_"
        lines.append(f"| `{h.module}` | `{h.file}` | `{asset}` |")
    lines.append("")
    return "\n".join(lines)


def _render_workflows(inv: Inventory) -> str:
    lines = [
        "## GitHub Actions workflows",
        "",
        "| File | Workflow name |",
        "|---|---|",
    ]
    for w in inv.workflows:
        lines.append(f"| `{w.file}` | {w.name} |")
    lines.append("")
    return "\n".join(lines)


def _render_tests(inv: Inventory) -> str:
    unit_total = sum(t.test_count for t in inv.unit_tests)
    integ_total = sum(t.test_count for t in inv.integration_tests)
    lines = [
        "## Tests",
        "",
        (
            f"Unit: **{len(inv.unit_tests)}** files, "
            f"**{unit_total}** test functions. "
            f"Integration: **{len(inv.integration_tests)}** files, "
            f"**{integ_total}** test functions."
        ),
        "",
        "### Unit tests (`tests/v2/`)",
        "",
        "| File | Test functions |",
        "|---|---:|",
    ]
    for t in inv.unit_tests:
        lines.append(f"| `{t.file}` | {t.test_count} |")
    lines.append("")
    lines.append("### Integration tests (`tests/integration/`)")
    lines.append("")
    lines.append("| File | Test functions |")
    lines.append("|---|---:|")
    for t in inv.integration_tests:
        lines.append(f"| `{t.file}` | {t.test_count} |")
    lines.append("")
    return "\n".join(lines)


def _render_mitre_coverage(inv: Inventory) -> str:
    """Headline MITRE coverage. Anchored to the curated matrix; matches
    the README badge and the ``contentops portfolio`` footer."""
    if inv.mitre_coverage is None:
        return ""
    mc = inv.mitre_coverage
    return "\n".join([
        "## MITRE ATT&CK coverage",
        "",
        f"- Covered: **{mc.covered}** / {mc.total} techniques (**{mc.pct}%**)",
        f"- Matrix: {mc.matrix_label}",
        "- Badge: see `coverage/badge.json` (shields.io endpoint format).",
        "- Layer: see `coverage/navigator-layer.json` (uploadable to "
        "https://mitre-attack.github.io/attack-navigator/).",
        "- Source helper: `contentops.coverage.coverage_summary()`.",
        "",
    ])


def render_markdown(inv: Inventory) -> str:
    """Return the canonical markdown body for ``inv``.

    The output is deterministic: same input always produces the
    byte-identical string. Newline at end-of-file kept so editors and
    git diff don't churn on whitespace.
    """
    sections = [
        _HEADER,
        _render_commands(inv),
        _render_traceability(inv),
        _render_assets(inv),
        _render_lint_rules(inv),
        _render_handlers(inv),
        _render_workflows(inv),
        _render_tests(inv),
        _render_mitre_coverage(inv),
    ]
    return "\n".join(sections).rstrip() + "\n"


__all__ = ["GENERATED_FILE", "render_markdown"]
