# SPDX-FileCopyrightText: 2026 KustoKing / SecM8
# SPDX-License-Identifier: Apache-2.0

"""Render the configuration-status markdown for ``docs/status/configuration.md``.

Reads :class:`contentops.devex.conformance.ConformanceReport` for the
configured layer scope and produces a self-contained markdown page: a
summary line, one section per layer, and a Check/Status/Detail/
Remediation table per layer.

Pure rendering -- the caller runs
:func:`contentops.devex.conformance.run_conformance` and passes the
report in. That keeps the renderer importable in tests without
needing real tenant config.

Every ``detail`` and ``remediation`` cell flows through
:func:`contentops.status.redact.redact` before rendering. L3-L7 checks
emit tenant GUIDs, subscription IDs, and full ARM resource paths;
without the redactor those would land in the committed page. See
:mod:`contentops.status.redact` for the redaction contract.
"""

from __future__ import annotations

from datetime import datetime, timezone

from contentops.devex.conformance import ConformanceCheck, ConformanceReport
from contentops.status.redact import redact

_STATUS_GLYPH = {
    "PASS": "✅",
    "FAIL": "❌",
    "SKIP": "⚪",
    "INFO": "ℹ️",
}


def _escape_cell(value: str) -> str:
    """Escape pipes + collapse newlines so a value renders in one table cell."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _summary_counts(checks: list[ConformanceCheck]) -> dict[str, int]:
    counts = {"PASS": 0, "FAIL": 0, "SKIP": 0, "INFO": 0}
    for check in checks:
        counts[check.status] = counts.get(check.status, 0) + 1
    return counts


def render_configuration(
    report: ConformanceReport,
    *,
    generated_at: datetime | None = None,
) -> str:
    """Render ``report`` as the configuration-status markdown page.

    ``generated_at`` is injected for deterministic test output; falls
    back to the current UTC time.
    """
    now = generated_at or datetime.now(timezone.utc)
    lines: list[str] = []
    lines.append("# Configuration status")
    lines.append("")
    lines.append(
        f"> Last refreshed {now.strftime('%Y-%m-%d %H:%M UTC')} -- "
        "regenerated by [the status-refresh workflow]"
        "(../../.github/workflows/status-refresh.yml). "
        "Auto-generated by `contentops status configuration`; do not edit "
        "by hand."
    )
    lines.append("")

    counts = _summary_counts(report.checks)
    summary_bits = [
        f"{_STATUS_GLYPH['PASS']} {counts.get('PASS', 0)} passed",
        f"{_STATUS_GLYPH['FAIL']} {counts.get('FAIL', 0)} failed",
        f"{_STATUS_GLYPH['SKIP']} {counts.get('SKIP', 0)} skipped",
    ]
    if counts.get("INFO"):
        summary_bits.append(f"{_STATUS_GLYPH['INFO']} {counts['INFO']} info")
    lines.append(f"**Scope:** {', '.join(report.scope) if report.scope else 'all'}  ")
    lines.append(f"**Summary:** {' · '.join(summary_bits)}")
    lines.append("")

    # Group checks by layer, preserving the order they appear in the report.
    by_layer: dict[str, list[ConformanceCheck]] = {}
    for check in report.checks:
        by_layer.setdefault(check.layer, []).append(check)

    if not by_layer:
        lines.append("_No checks in scope._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for layer in sorted(by_layer):
        layer_checks = by_layer[layer]
        layer_counts = _summary_counts(layer_checks)
        verdict = (
            _STATUS_GLYPH["FAIL"] if layer_counts.get("FAIL", 0) > 0
            else _STATUS_GLYPH["PASS"]
        )
        lines.append(f"## {layer} {verdict}")
        lines.append("")
        lines.append("| Check | Status | Detail | Remediation |")
        lines.append("|---|---|---|---|")
        for check in layer_checks:
            glyph = _STATUS_GLYPH.get(check.status, check.status)
            # Redact tenant identifiers BEFORE escaping so the pipe-escape
            # logic doesn't get confused by mid-redaction backslashes.
            detail = _escape_cell(redact(check.detail))
            remediation = _escape_cell(redact(check.remediation))
            lines.append(
                f"| `{_escape_cell(redact(check.name))}` "
                f"| {glyph} {check.status} "
                f"| {detail or '—'} "
                f"| {remediation or '—'} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


__all__ = ["render_configuration"]
