# SPDX-FileCopyrightText: 2026 KustoKing / SecM8
# SPDX-License-Identifier: Apache-2.0

"""Render the deployment-status markdown for ``docs/status/deployments.md``.

Joins three sources to answer "what's deployed where, when, by which
SHA, and was the last apply OK?":

* :func:`contentops.core.discovery.discover_assets` → assets known to git
* :class:`contentops.state.EnvState` → assets the pipeline remembers applying
* :func:`contentops.audit_query.query_latest` (via a single-pass index
  built here for performance) → the last audit record per asset id

Each row is classified as one of:

* ``in-sync``    — present in both git and state, last apply was success.
* ``failed``     — present in both, but the last apply or audit says failed.
* ``unmanaged``  — present in git, never applied (no state entry).
* ``orphan``     — present in state, no longer in git (deployment ghost).

Pure rendering — the caller decides which audit dir / state file to
read. The CLI wrapper provides sensible defaults (``state/state.json``,
``audit/``, ``detections/``).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from contentops.audit_filter import iter_records
from contentops.core.discovery import iter_loaded_assets
from contentops.state import EnvState

_CLASS_GLYPH = {
    "in-sync": "✅",
    "failed": "❌",
    "unmanaged": "⚪",
    "orphan": "⚠️",
}


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _short_sha(sha: str) -> str:
    return sha[:8] if sha else ""


def _latest_audit_index(audit_dir: Path) -> dict[str, dict]:
    """Return ``envelope_id -> latest audit record`` across the whole chain.

    Single linear pass over every record — much faster than calling
    :func:`contentops.audit_query.query_latest` once per asset, which
    iterates the chain anew each time.
    """
    if not audit_dir.is_dir():
        return {}
    latest: dict[str, dict] = {}
    files = sorted(audit_dir.glob("*.jsonl"))
    for rec in iter_records(files):
        envelope_id = str(rec.get("id") or "")
        if not envelope_id:
            continue
        ts = str(rec.get("timestamp") or "")
        prev = latest.get(envelope_id)
        if prev is None or ts > str(prev.get("timestamp") or ""):
            latest[envelope_id] = rec
    return latest


def _classify(
    *,
    in_git: bool,
    in_state: bool,
    state_status: str,
    last_audit_status: str,
) -> str:
    if not in_git and in_state:
        return "orphan"
    if in_git and not in_state:
        return "unmanaged"
    # in both
    if state_status == "failed" or last_audit_status == "failed":
        return "failed"
    return "in-sync"


def _discover_kinds(
    *,
    detections_root: Path,
    state: EnvState,
) -> dict[str, dict[str, dict]]:
    """Build ``asset_kind -> envelope_id -> row data`` from git + state.

    Each row dict carries the metadata needed for the classifier and
    the table cells. Git is iterated once; state is iterated once.
    """
    rows: dict[str, dict[str, dict]] = {}

    # Git-side: every YAML we can load contributes an envelope id.
    if detections_root.is_dir():
        # Malformed files are skipped (silent) — lint catches them; the
        # status report must never crash on a single bad YAML.
        for la in iter_loaded_assets(detections_root):
            kind = la.envelope.asset.value
            entry = rows.setdefault(kind, {}).setdefault(la.envelope.id, {})
            entry["in_git"] = True
            entry["path"] = str(la.path)
            entry["workspace"] = getattr(la.envelope, "workspace", "") or ""

    # State-side: every managed entry contributes too (catches orphans).
    for kind, bucket in state.managed_assets.items():
        for envelope_id, state_entry in bucket.items():
            entry = rows.setdefault(kind, {}).setdefault(envelope_id, {})
            entry["in_state"] = True
            entry["state_status"] = state_entry.status or ""
            entry["last_applied_at"] = state_entry.last_applied_at or ""
            entry["last_applied_sha"] = state_entry.last_applied_sha or ""
            entry["remote_id"] = state_entry.remote_id or ""

    return rows


_WORKFLOW_LINK = (
    "regenerated by [the status-refresh workflow]"
    "(../../.github/workflows/status-refresh.yml)"
)


def render_deployments(
    *,
    detections_root: Path,
    state: EnvState,
    audit_dir: Path,
    generated_at: datetime | None = None,
    failures_only: bool = False,
) -> str:
    """Render the deployment-status markdown page.

    ``failures_only`` collapses the rendered table to just ``failed``
    and ``orphan`` rows (the actionable classes). The **Totals:**
    summary line at the top still reflects the full counts so the
    reader sees the full picture even in filtered view.
    """
    now = generated_at or datetime.now(timezone.utc)
    audit_index = _latest_audit_index(audit_dir)
    by_kind = _discover_kinds(detections_root=detections_root, state=state)

    lines: list[str] = []
    lines.append("# Deployment status")
    lines.append("")
    lines.append(
        f"> Last refreshed {now.strftime('%Y-%m-%d %H:%M UTC')} -- "
        f"{_WORKFLOW_LINK}. Auto-generated by "
        f"`contentops status deployments`; do not edit by hand."
    )
    lines.append("")
    if failures_only:
        lines.append(
            "_Filtered to `failed` + `orphan` rows only "
            "(`--failures-only`). Totals reflect the full set._"
        )
        lines.append("")

    # Top-line: env + last-apply pointer
    if state.env or state.last_apply_at or state.last_apply_sha:
        env_label = state.env or "(no env)"
        last_at = state.last_apply_at or "—"
        last_sha = _short_sha(state.last_apply_sha) or "—"
        lines.append(
            f"**Env:** `{env_label}` · **Last apply:** {last_at} · "
            f"**SHA:** `{last_sha}`"
        )
        lines.append("")

    # Global summary across all kinds
    totals = {"in-sync": 0, "failed": 0, "unmanaged": 0, "orphan": 0}
    for kind_rows in by_kind.values():
        for envelope_id, data in kind_rows.items():
            audit_rec = audit_index.get(envelope_id, {})
            cls = _classify(
                in_git=bool(data.get("in_git")),
                in_state=bool(data.get("in_state")),
                state_status=str(data.get("state_status") or ""),
                last_audit_status=str(audit_rec.get("status") or ""),
            )
            totals[cls] += 1
            data["_class"] = cls
            data["_audit"] = audit_rec

    summary_bits = [
        f"{_CLASS_GLYPH['in-sync']} {totals['in-sync']} in-sync",
        f"{_CLASS_GLYPH['failed']} {totals['failed']} failed",
        f"{_CLASS_GLYPH['unmanaged']} {totals['unmanaged']} unmanaged",
        f"{_CLASS_GLYPH['orphan']} {totals['orphan']} orphan",
    ]
    lines.append(f"**Totals:** {' · '.join(summary_bits)}")
    lines.append("")

    if not by_kind:
        lines.append("_No detections discovered under `detections/` and no managed assets in state._")
        lines.append("")
        return "\n".join(lines) + "\n"

    actionable = {"failed", "orphan"}
    for kind in sorted(by_kind):
        kind_rows = by_kind[kind]
        # Per-kind subtotal row — same glyph order as global totals.
        kind_counts = {"in-sync": 0, "failed": 0, "unmanaged": 0, "orphan": 0}
        for data in kind_rows.values():
            kind_counts[data["_class"]] += 1

        # In failures-only mode, skip kinds with zero actionable rows.
        if failures_only and (kind_counts["failed"] + kind_counts["orphan"]) == 0:
            continue

        lines.append(f"## `{kind}` ({len(kind_rows)} assets)")
        lines.append("")
        lines.append(
            f"{_CLASS_GLYPH['in-sync']} {kind_counts['in-sync']} in-sync · "
            f"{_CLASS_GLYPH['failed']} {kind_counts['failed']} failed · "
            f"{_CLASS_GLYPH['unmanaged']} {kind_counts['unmanaged']} unmanaged · "
            f"{_CLASS_GLYPH['orphan']} {kind_counts['orphan']} orphan"
        )
        lines.append("")
        lines.append(
            "| Asset ID | Class | Last Applied | SHA | Last Audit | Workspace |"
        )
        lines.append("|---|---|---|---|---|---|")
        for envelope_id in sorted(kind_rows):
            data = kind_rows[envelope_id]
            audit_rec = data.get("_audit") or {}
            cls = data["_class"]
            if failures_only and cls not in actionable:
                continue
            cells = [
                f"`{_escape_cell(envelope_id)}`",
                f"{_CLASS_GLYPH.get(cls, '')} {cls}",
                _escape_cell(data.get("last_applied_at") or "—"),
                f"`{_short_sha(data.get('last_applied_sha') or '')}`" if data.get("last_applied_sha") else "—",
                (
                    f"{audit_rec.get('action', '')} "
                    f"({audit_rec.get('status', '')})"
                    if audit_rec else "—"
                ),
                f"`{_escape_cell(data.get('workspace') or '')}`" if data.get("workspace") else "—",
            ]
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    return "\n".join(lines) + "\n"


__all__ = ["render_deployments"]
