# SPDX-FileCopyrightText: 2026 KustoKing / SecM8
# SPDX-License-Identifier: Apache-2.0

"""Render a WHATSNEW markdown body from one or more ManifestDiff results."""

from __future__ import annotations

from typing import Any

from contentops.upstream.manifest import ManifestDiff


def _entry_label(entry: dict[str, Any]) -> str:
    """Compact label for a manifest entry — `<displayName> (<name>)`."""
    display = entry.get("displayName") or entry.get("name") or "<unknown>"
    name = entry.get("name") or ""
    if name and name != display:
        return f"{display} (`{name}`)"
    return f"`{display}`"


def _version_pair(old: dict[str, Any], new: dict[str, Any]) -> str:
    old_v = old.get("version") or "?"
    new_v = new.get("version") or "?"
    if old_v == new_v:
        return ""
    return f" — version `{old_v}` → `{new_v}`"


def _render_section(title: str, diff: ManifestDiff) -> list[str]:
    """One section per source (marketplace / templates). Returns lines."""
    lines: list[str] = [f"## {title}", ""]
    if diff.is_empty:
        lines.append("_No changes._")
        lines.append("")
        return lines
    if diff.added:
        lines.append(f"### Added ({len(diff.added)})")
        for e in diff.added:
            v = f" (version `{e.get('version') or '?'}`)" if e.get("version") else ""
            lines.append(f"- {_entry_label(e)}{v}")
        lines.append("")
    if diff.changed:
        lines.append(f"### Changed ({len(diff.changed)})")
        for old, new in diff.changed:
            lines.append(f"- {_entry_label(new)}{_version_pair(old, new)}")
        lines.append("")
    if diff.removed:
        lines.append(f"### Removed ({len(diff.removed)})")
        for e in diff.removed:
            lines.append(f"- {_entry_label(e)}")
        lines.append("")
    return lines


_SOURCE_TO_COMMAND: dict[str, str] = {
    "Content Packages": "contentops upstream check-marketplace",
    "Alert Rule Templates": "contentops upstream check-templates",
    "KQL workspace schemas": "contentops upstream check-schemas",
    "Defender XDR schemas": "contentops upstream check-defender-schema",
}


def _byline_for_sources(sources: list[str]) -> str:
    """Derive a 'Auto-generated by ...' byline from the diff source labels.

    Falls back to a generic mention of the ``contentops upstream`` group
    when a source label isn't in the known-mapping (forward-compat).
    """
    commands: list[str] = []
    for source in sources:
        cmd = _SOURCE_TO_COMMAND.get(source)
        if cmd and cmd not in commands:
            commands.append(cmd)
    if not commands:
        return (
            "Auto-generated by `contentops upstream` watchers. Review the "
            "entries below before adopting any changes."
        )
    if len(commands) == 1:
        return (
            f"Auto-generated by `{commands[0]}`. Review the entries below "
            "before adopting any changes."
        )
    joined = ", ".join(f"`{c}`" for c in commands[:-1])
    return (
        f"Auto-generated by {joined} and `{commands[-1]}`. "
        "Review the entries below before adopting any changes."
    )


def render_markdown(date: str, diffs_by_source: dict[str, ManifestDiff]) -> str:
    """Build the markdown body for ``docs/whats-new/<date>.md``.

    ``diffs_by_source`` is e.g. ``{"Content Packages": diff1, "Alert Rule
    Templates": diff2}``. The renderer keeps the source order stable
    (insertion order in Python 3.7+) and derives the byline from the
    set of source labels (so a `check-schemas`-only run doesn't
    misleadingly claim to be from `check-marketplace`).
    """
    sources = list(diffs_by_source.keys())
    out: list[str] = [
        f"# Upstream catalog changes — {date}",
        "",
        _byline_for_sources(sources),
        "",
    ]
    for source, diff in diffs_by_source.items():
        out.extend(_render_section(source, diff))
    return "\n".join(out).rstrip() + "\n"


__all__ = ["render_markdown"]
